---
version: "2.1"
services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    depends_on:
       - unifi-mongodb
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Toronto
      - MONGO_USER=unifi
      - MONGO_PASS=$PASSWORD
      - MONGO_HOST=unifi-mongodb
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1536 #optional
      - MEM_STARTUP=1024 #optional
      #- MONGO_TLS= #optional
      #- MONGO_AUTHSOURCE= #optional
    volumes:
      - /mnt/sharedata/unifi-mongo-controller/data/config:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1901:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped

#Using Mongo Database 4.4

  unifi-mongodb:
    image: docker.io/mongo:4.4
    container_name: unifi-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=unifi-db
      - TZ=America/Toronto
    volumes:
       - /mnt/sharedata/unifi-mongo-controller/unifi-db/data:/data/db
       - /mnt/sharedata/unifi-mongo-controller/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped
